# Generated by Django 3.2.16 on 2023-03-19 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_auto_20230319_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='dni',
            field=models.IntegerField(default=1),
        ),
    ]
