# Generated by Django 3.2.16 on 2023-03-19 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_vendedor_dni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentacion',
            name='precio',
        ),
    ]
