# Generated by Django 3.2.16 on 2023-03-19 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_remove_presentacion_precio'),
        ('facturas', '0002_alter_lineitem_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitem',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.ticket'),
        ),
    ]
